// Code generated by protoc-gen-go-kernel. DO NOT EDIT.
// versions:
// - protoc-gen-go-kernel dev
// source: todo/v1/todo.proto

package v1

import (
	context "context"
	accessx "github.com/aisphereio/kernel/accessx"
	v1 "github.com/aisphereio/kernel/api/aisphere/access/v1"
	authz "github.com/aisphereio/kernel/authz"
	requestx "github.com/aisphereio/kernel/requestx"
	serverx "github.com/aisphereio/kernel/serverx"
)

// TodoServiceKernelModule returns the generated Kernel service module for todo.v1.TodoService.
func TodoServiceKernelModule() serverx.ServiceModule {
	return serverx.ServiceModule{
		Name:                "todo-service",
		GatewayManifest:     TodoServiceGatewayManifest(),
		RequestInfoResolver: TodoServiceKernelRequestInfoResolver,
		AccessResolver:      TodoServiceKernelAccessResolver,
	}
}

var TodoServiceKernelAuthzRules = authz.Rules{
	"/todo.v1.TodoService/CreateTodo": {
		Service:    "todo.v1.TodoService",
		Method:     "CreateTodo",
		FullMethod: "/todo.v1.TodoService/CreateTodo",
		Action:     "create",
		Resource:   "todo:collection",
		Audience:   "todo-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "todo.create",
		AuditRisk:  "low",
	},
	"/todo.v1.TodoService/GetTodo": {
		Service:    "todo.v1.TodoService",
		Method:     "GetTodo",
		FullMethod: "/todo.v1.TodoService/GetTodo",
		Action:     "read",
		Resource:   "todo:{id}",
		Audience:   "todo-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "todo.get",
		AuditRisk:  "low",
	},
	"/todo.v1.TodoService/ListTodos": {
		Service:    "todo.v1.TodoService",
		Method:     "ListTodos",
		FullMethod: "/todo.v1.TodoService/ListTodos",
		Action:     "read",
		Resource:   "todo:collection",
		Audience:   "todo-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "todo.list",
		AuditRisk:  "low",
	},
	"/todo.v1.TodoService/UpdateTodo": {
		Service:    "todo.v1.TodoService",
		Method:     "UpdateTodo",
		FullMethod: "/todo.v1.TodoService/UpdateTodo",
		Action:     "update",
		Resource:   "todo:{todo.id}",
		Audience:   "todo-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "todo.update",
		AuditRisk:  "medium",
	},
	"/todo.v1.TodoService/DeleteTodo": {
		Service:    "todo.v1.TodoService",
		Method:     "DeleteTodo",
		FullMethod: "/todo.v1.TodoService/DeleteTodo",
		Action:     "delete",
		Resource:   "todo:{id}",
		Audience:   "todo-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "todo.delete",
		AuditRisk:  "high",
	},
	"/todo.v1.TodoService/WatchTodos": {
		Service:    "todo.v1.TodoService",
		Method:     "WatchTodos",
		FullMethod: "/todo.v1.TodoService/WatchTodos",
		Action:     "watch",
		Resource:   "todo:collection",
		Audience:   "todo-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "todo.watch",
		AuditRisk:  "low",
	},
	"/todo.v1.TodoService/SyncTodos": {
		Service:    "todo.v1.TodoService",
		Method:     "SyncTodos",
		FullMethod: "/todo.v1.TodoService/SyncTodos",
		Action:     "sync",
		Resource:   "todo:collection",
		Audience:   "todo-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "todo.sync",
		AuditRisk:  "medium",
	},
}

// TodoServiceKernelRequestInfoResolver maps proto access policy into requestx.Info for serverx modules.
func TodoServiceKernelRequestInfoResolver(ctx context.Context, operation string, req any) (requestx.Info, bool, error) {
	_ = ctx
	_ = req
	switch _TodoServiceKernelNormalizeOperation(operation) {
	case "/todo.v1.TodoService/CreateTodo":
		info := requestx.Info{
			Service:       "todo.v1.TodoService",
			Method:        "CreateTodo",
			Operation:     "/todo.v1.TodoService/CreateTodo",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "create",
			Resource:      "todo:collection",
			TargetService: "todo-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "todo.create"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	case "/todo.v1.TodoService/GetTodo":
		info := requestx.Info{
			Service:       "todo.v1.TodoService",
			Method:        "GetTodo",
			Operation:     "/todo.v1.TodoService/GetTodo",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "read",
			Resource:      "todo:{id}",
			TargetService: "todo-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "todo.get"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	case "/todo.v1.TodoService/ListTodos":
		info := requestx.Info{
			Service:       "todo.v1.TodoService",
			Method:        "ListTodos",
			Operation:     "/todo.v1.TodoService/ListTodos",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "read",
			Resource:      "todo:collection",
			TargetService: "todo-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "todo.list"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	case "/todo.v1.TodoService/UpdateTodo":
		info := requestx.Info{
			Service:       "todo.v1.TodoService",
			Method:        "UpdateTodo",
			Operation:     "/todo.v1.TodoService/UpdateTodo",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "update",
			Resource:      "todo:{todo.id}",
			TargetService: "todo-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "todo.update"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/todo.v1.TodoService/DeleteTodo":
		info := requestx.Info{
			Service:       "todo.v1.TodoService",
			Method:        "DeleteTodo",
			Operation:     "/todo.v1.TodoService/DeleteTodo",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "delete",
			Resource:      "todo:{id}",
			TargetService: "todo-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "todo.delete"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/todo.v1.TodoService/WatchTodos":
		info := requestx.Info{
			Service:       "todo.v1.TodoService",
			Method:        "WatchTodos",
			Operation:     "/todo.v1.TodoService/WatchTodos",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "watch",
			Resource:      "todo:collection",
			TargetService: "todo-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "todo.watch"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	case "/todo.v1.TodoService/SyncTodos":
		info := requestx.Info{
			Service:       "todo.v1.TodoService",
			Method:        "SyncTodos",
			Operation:     "/todo.v1.TodoService/SyncTodos",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "sync",
			Resource:      "todo:collection",
			TargetService: "todo-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "todo.sync"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	default:
		return requestx.Info{}, false, nil
	}
}

// TodoServiceKernelAccessResolver maps proto authz policy into accessx.Check for serverx modules.
func TodoServiceKernelAccessResolver(ctx context.Context, operation string, req any) (accessx.Check, bool, error) {
	rule, ok := TodoServiceKernelAuthzRules[_TodoServiceKernelNormalizeOperation(operation)]
	if !ok || rule.Action == "" {
		return accessx.Check{}, false, nil
	}
	resource, err := (authz.RuleResolver{}).ResolveResource(rule, req)
	if err != nil {
		return accessx.Check{}, true, err
	}
	_ = ctx
	check := accessx.Check{
		Permission:  rule.Action,
		Resource:    resource,
		AuditAction: rule.AuditEvent,
		Metadata:    map[string]any{"authz_rule": rule.FullMethod, "authz_mode": string(rule.Mode)},
	}
	if check.AuditAction == "" {
		check.AuditAction = rule.Action
	}
	return check, true, nil
}

func _TodoServiceKernelNormalizeOperation(operation string) string {
	switch operation {
	case "CreateTodo", "todo.v1.TodoService/CreateTodo":
		return "/todo.v1.TodoService/CreateTodo"
	case "GetTodo", "todo.v1.TodoService/GetTodo":
		return "/todo.v1.TodoService/GetTodo"
	case "ListTodos", "todo.v1.TodoService/ListTodos":
		return "/todo.v1.TodoService/ListTodos"
	case "UpdateTodo", "todo.v1.TodoService/UpdateTodo":
		return "/todo.v1.TodoService/UpdateTodo"
	case "DeleteTodo", "todo.v1.TodoService/DeleteTodo":
		return "/todo.v1.TodoService/DeleteTodo"
	case "WatchTodos", "todo.v1.TodoService/WatchTodos":
		return "/todo.v1.TodoService/WatchTodos"
	case "SyncTodos", "todo.v1.TodoService/SyncTodos":
		return "/todo.v1.TodoService/SyncTodos"
	default:
		return operation
	}
}
