// Code generated by protoc-gen-go-gateway. DO NOT EDIT.
// versions:
// - protoc-gen-go-gateway dev
// source: todo/v1/todo.proto

package v1

import (
	v1 "github.com/aisphereio/kernel/api/aisphere/access/v1"
	gatewayx "github.com/aisphereio/kernel/gatewayx"
	strconv "strconv"
)

// TodoServiceGatewayManifest returns the generated Gateway route manifest for todo.v1.TodoService.
func TodoServiceGatewayManifest() gatewayx.Manifest {
	return gatewayx.Manifest{
		Service:   "todo-service",
		Namespace: "aisphere",
		Routes: []gatewayx.GatewayRoute{
			{
				ID:       "todo.create.todo",
				Method:   "POST",
				Path:     "/v1/todos/create",
				Upstream: gatewayx.UpstreamRef{Service: "todo-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/todo.v1.TodoService/CreateTodo"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true, Profiles: nil, Tags: nil},
			},
			{
				ID:       "todo.get.todo",
				Method:   "GET",
				Path:     "/v1/todos/{id}",
				Upstream: gatewayx.UpstreamRef{Service: "todo-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/todo.v1.TodoService/GetTodo"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true, Profiles: nil, Tags: nil},
			},
			{
				ID:       "todo.list.todos",
				Method:   "GET",
				Path:     "/v1/todos/list",
				Upstream: gatewayx.UpstreamRef{Service: "todo-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/todo.v1.TodoService/ListTodos"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true, Profiles: nil, Tags: nil},
			},
			{
				ID:       "todo.update.todo",
				Method:   "PUT",
				Path:     "/v1/todos/update",
				Upstream: gatewayx.UpstreamRef{Service: "todo-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/todo.v1.TodoService/UpdateTodo"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true, Profiles: nil, Tags: nil},
			},
			{
				ID:       "todo.delete.todo",
				Method:   "DELETE",
				Path:     "/v1/todos/{id}",
				Upstream: gatewayx.UpstreamRef{Service: "todo-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/todo.v1.TodoService/DeleteTodo"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true, Profiles: nil, Tags: nil},
			},
		},
	}
}

// TodoServiceGatewayBindCreateTodo binds the matched HTTP Gateway request to the gRPC request for /todo.v1.TodoService/CreateTodo.
func TodoServiceGatewayBindCreateTodo(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*CreateTodoRequest, error) {
	out := &CreateTodoRequest{}
	if v, ok := req.Body.(*CreateTodoRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(CreateTodoRequest); ok {
		out = &v
	}
	return out, nil
}

// TodoServiceGatewayBindGetTodo binds the matched HTTP Gateway request to the gRPC request for /todo.v1.TodoService/GetTodo.
func TodoServiceGatewayBindGetTodo(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*GetTodoRequest, error) {
	out := &GetTodoRequest{}
	if v, ok := req.Body.(*GetTodoRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(GetTodoRequest); ok {
		out = &v
	}
	if v := match.Params["id"]; v != "" {
		parsed, err := strconv.ParseInt(v, 10, 64)
		if err != nil {
			return nil, err
		}
		out.Id = parsed
	}
	return out, nil
}

// TodoServiceGatewayBindListTodos binds the matched HTTP Gateway request to the gRPC request for /todo.v1.TodoService/ListTodos.
func TodoServiceGatewayBindListTodos(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*ListTodosRequest, error) {
	out := &ListTodosRequest{}
	if v, ok := req.Body.(*ListTodosRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(ListTodosRequest); ok {
		out = &v
	}
	return out, nil
}

// TodoServiceGatewayBindUpdateTodo binds the matched HTTP Gateway request to the gRPC request for /todo.v1.TodoService/UpdateTodo.
func TodoServiceGatewayBindUpdateTodo(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*UpdateTodoRequest, error) {
	out := &UpdateTodoRequest{}
	if v, ok := req.Body.(*UpdateTodoRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(UpdateTodoRequest); ok {
		out = &v
	}
	return out, nil
}

// TodoServiceGatewayBindDeleteTodo binds the matched HTTP Gateway request to the gRPC request for /todo.v1.TodoService/DeleteTodo.
func TodoServiceGatewayBindDeleteTodo(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*DeleteTodoRequest, error) {
	out := &DeleteTodoRequest{}
	if v, ok := req.Body.(*DeleteTodoRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(DeleteTodoRequest); ok {
		out = &v
	}
	if v := match.Params["id"]; v != "" {
		parsed, err := strconv.ParseInt(v, 10, 64)
		if err != nil {
			return nil, err
		}
		out.Id = parsed
	}
	return out, nil
}

// RegisterTodoServiceGatewayInvokers registers generated Gateway -> gRPC operation invokers for todo.v1.TodoService.
func RegisterTodoServiceGatewayInvokers(registry *gatewayx.InvokerRegistry, client TodoServiceClient) error {
	if err := registry.Register("/todo.v1.TodoService/CreateTodo", gatewayx.GRPCUnaryInvoker(TodoServiceGatewayBindCreateTodo, client.CreateTodo)); err != nil {
		return err
	}
	if err := registry.Register("/todo.v1.TodoService/GetTodo", gatewayx.GRPCUnaryInvoker(TodoServiceGatewayBindGetTodo, client.GetTodo)); err != nil {
		return err
	}
	if err := registry.Register("/todo.v1.TodoService/ListTodos", gatewayx.GRPCUnaryInvoker(TodoServiceGatewayBindListTodos, client.ListTodos)); err != nil {
		return err
	}
	if err := registry.Register("/todo.v1.TodoService/UpdateTodo", gatewayx.GRPCUnaryInvoker(TodoServiceGatewayBindUpdateTodo, client.UpdateTodo)); err != nil {
		return err
	}
	if err := registry.Register("/todo.v1.TodoService/DeleteTodo", gatewayx.GRPCUnaryInvoker(TodoServiceGatewayBindDeleteTodo, client.DeleteTodo)); err != nil {
		return err
	}
	return nil
}
