// Code generated by protoc-gen-go-authz. DO NOT EDIT.
// versions:
// - protoc-gen-go-authz dev
// source: todo/v1/todo.proto

package v1

import (
	context "context"
	accessx "github.com/aisphereio/kernel/accessx"
	v1 "github.com/aisphereio/kernel/api/aisphere/access/v1"
	authz "github.com/aisphereio/kernel/authz"
	contextx "github.com/aisphereio/kernel/contextx"
	requestx "github.com/aisphereio/kernel/requestx"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	strings "strings"
)

var _ = grpc.EmptyCallOption{}

var TodoServiceAuthzRules = authz.Rules{
	"/todo.v1.TodoService/CreateTodo": {
		Service:    "todo.v1.TodoService",
		Method:     "CreateTodo",
		FullMethod: "/todo.v1.TodoService/CreateTodo",
		Action:     "create",
		Resource:   "todo:collection",
		Audience:   "todo-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "todo.create",
		AuditRisk:  "low",
	},
	"/todo.v1.TodoService/GetTodo": {
		Service:    "todo.v1.TodoService",
		Method:     "GetTodo",
		FullMethod: "/todo.v1.TodoService/GetTodo",
		Action:     "read",
		Resource:   "todo:{id}",
		Audience:   "todo-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "todo.get",
		AuditRisk:  "low",
	},
	"/todo.v1.TodoService/ListTodos": {
		Service:    "todo.v1.TodoService",
		Method:     "ListTodos",
		FullMethod: "/todo.v1.TodoService/ListTodos",
		Action:     "read",
		Resource:   "todo:collection",
		Audience:   "todo-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "todo.list",
		AuditRisk:  "low",
	},
	"/todo.v1.TodoService/UpdateTodo": {
		Service:    "todo.v1.TodoService",
		Method:     "UpdateTodo",
		FullMethod: "/todo.v1.TodoService/UpdateTodo",
		Action:     "update",
		Resource:   "todo:{todo.id}",
		Audience:   "todo-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "todo.update",
		AuditRisk:  "medium",
	},
	"/todo.v1.TodoService/DeleteTodo": {
		Service:    "todo.v1.TodoService",
		Method:     "DeleteTodo",
		FullMethod: "/todo.v1.TodoService/DeleteTodo",
		Action:     "delete",
		Resource:   "todo:{id}",
		Audience:   "todo-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "todo.delete",
		AuditRisk:  "high",
	},
	"/todo.v1.TodoService/WatchTodos": {
		Service:    "todo.v1.TodoService",
		Method:     "WatchTodos",
		FullMethod: "/todo.v1.TodoService/WatchTodos",
		Action:     "watch",
		Resource:   "todo:collection",
		Audience:   "todo-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "todo.watch",
		AuditRisk:  "low",
	},
	"/todo.v1.TodoService/SyncTodos": {
		Service:    "todo.v1.TodoService",
		Method:     "SyncTodos",
		FullMethod: "/todo.v1.TodoService/SyncTodos",
		Action:     "sync",
		Resource:   "todo:collection",
		Audience:   "todo-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "todo.sync",
		AuditRisk:  "medium",
	},
}

const TodoServiceAuthzManifestJSON = `{
  "methods": [
    {
      "service": "todo.v1.TodoService",
      "method": "CreateTodo",
      "full_method": "/todo.v1.TodoService/CreateTodo",
      "action": "create",
      "resource": "todo:collection",
      "audience": "todo-service",
      "mode": "CHECK_ONLY",
      "audit_event": "todo.create",
      "audit_risk": "low"
    },
    {
      "service": "todo.v1.TodoService",
      "method": "GetTodo",
      "full_method": "/todo.v1.TodoService/GetTodo",
      "action": "read",
      "resource": "todo:{id}",
      "audience": "todo-service",
      "mode": "CHECK_ONLY",
      "audit_event": "todo.get",
      "audit_risk": "low"
    },
    {
      "service": "todo.v1.TodoService",
      "method": "ListTodos",
      "full_method": "/todo.v1.TodoService/ListTodos",
      "action": "read",
      "resource": "todo:collection",
      "audience": "todo-service",
      "mode": "CHECK_ONLY",
      "audit_event": "todo.list",
      "audit_risk": "low"
    },
    {
      "service": "todo.v1.TodoService",
      "method": "UpdateTodo",
      "full_method": "/todo.v1.TodoService/UpdateTodo",
      "action": "update",
      "resource": "todo:{todo.id}",
      "audience": "todo-service",
      "mode": "CHECK_ONLY",
      "audit_event": "todo.update",
      "audit_risk": "medium"
    },
    {
      "service": "todo.v1.TodoService",
      "method": "DeleteTodo",
      "full_method": "/todo.v1.TodoService/DeleteTodo",
      "action": "delete",
      "resource": "todo:{id}",
      "audience": "todo-service",
      "mode": "CHECK_ONLY",
      "audit_event": "todo.delete",
      "audit_risk": "high"
    },
    {
      "service": "todo.v1.TodoService",
      "method": "WatchTodos",
      "full_method": "/todo.v1.TodoService/WatchTodos",
      "action": "watch",
      "resource": "todo:collection",
      "audience": "todo-service",
      "mode": "CHECK_ONLY",
      "audit_event": "todo.watch",
      "audit_risk": "low"
    },
    {
      "service": "todo.v1.TodoService",
      "method": "SyncTodos",
      "full_method": "/todo.v1.TodoService/SyncTodos",
      "action": "sync",
      "resource": "todo:collection",
      "audience": "todo-service",
      "mode": "CHECK_ONLY",
      "audit_event": "todo.sync",
      "audit_risk": "medium"
    }
  ],
  "service": "todo.v1.TodoService"
}`

// TodoServiceRequestInfoResolver maps generated proto access policy into requestx.Info.
// It should be passed to autowire.WithRequestInfoResolver / WithClientRequestInfoResolver.
func TodoServiceRequestInfoResolver(ctx context.Context, operation string, req any) (requestx.Info, bool, error) {
	_ = ctx
	_ = req
	rule, ok := TodoServiceAuthzRules[operation]
	if !ok && operation != "" {
		rule, ok = TodoServiceAuthzRules[_TodoServiceNormalizeOperation(operation)]
	}
	if !ok {
		return requestx.Info{}, false, nil
	}
	info := requestx.Info{
		Service:       rule.Service,
		Method:        rule.Method,
		Operation:     rule.FullMethod,
		Exposure:      v1.Exposure_AUTHORIZED,
		Action:        rule.Action,
		Resource:      rule.Resource,
		TargetService: rule.Audience,
		Labels:        map[string]string{"authz_mode": string(rule.Mode)},
	}
	if rule.AuditEvent != "" {
		info.Labels["audit_event"] = rule.AuditEvent
	}
	if rule.AuditRisk != "" {
		info.Labels["audit_risk"] = rule.AuditRisk
	}
	if rule.Capability != "" {
		info.Labels["capability"] = rule.Capability
	}
	return info.Normalize(), true, nil
}

// TodoServiceAccessResolver maps generated proto authz rules into accessx.Check.
// It matches middleware/access.Resolver, so services can pass it directly to autowire.WithAccess.
func TodoServiceAccessResolver(ctx context.Context, operation string, req any) (accessx.Check, bool, error) {
	rule, ok := TodoServiceAuthzRules[operation]
	if !ok && operation != "" {
		rule, ok = TodoServiceAuthzRules[_TodoServiceNormalizeOperation(operation)]
	}
	if !ok || rule.Action == "" {
		return accessx.Check{}, false, nil
	}
	resource, err := (authz.RuleResolver{}).ResolveResource(rule, req)
	if err != nil {
		return accessx.Check{}, true, err
	}
	_ = ctx
	check := accessx.Check{
		Permission:  rule.Action,
		Resource:    resource,
		AuditAction: rule.AuditEvent,
		Metadata:    map[string]any{"authz_rule": rule.FullMethod, "authz_mode": string(rule.Mode)},
	}
	if check.AuditAction == "" {
		check.AuditAction = rule.Action
	}
	return check, true, nil
}

func _TodoServiceNormalizeOperation(operation string) string {
	switch operation {
	case "CreateTodo", "todo.v1.TodoService/CreateTodo":
		return "/todo.v1.TodoService/CreateTodo"
	case "GetTodo", "todo.v1.TodoService/GetTodo":
		return "/todo.v1.TodoService/GetTodo"
	case "ListTodos", "todo.v1.TodoService/ListTodos":
		return "/todo.v1.TodoService/ListTodos"
	case "UpdateTodo", "todo.v1.TodoService/UpdateTodo":
		return "/todo.v1.TodoService/UpdateTodo"
	case "DeleteTodo", "todo.v1.TodoService/DeleteTodo":
		return "/todo.v1.TodoService/DeleteTodo"
	case "WatchTodos", "todo.v1.TodoService/WatchTodos":
		return "/todo.v1.TodoService/WatchTodos"
	case "SyncTodos", "todo.v1.TodoService/SyncTodos":
		return "/todo.v1.TodoService/SyncTodos"
	default:
		return operation
	}
}

type TodoServiceSecureClient struct {
	raw      TodoServiceClient
	guard    authz.Guard
	resolver authz.RuleResolver
}

func NewTodoServiceSecureClient(raw TodoServiceClient, guard authz.Guard) *TodoServiceSecureClient {
	return &TodoServiceSecureClient{raw: raw, guard: guard, resolver: authz.RuleResolver{}}
}

var _ TodoServiceClient = (*TodoServiceSecureClient)(nil)

func (c *TodoServiceSecureClient) CreateTodo(ctx context.Context, in *CreateTodoRequest, opts ...grpc.CallOption) (*Todo, error) {
	if c != nil && c.guard != nil {
		rule := TodoServiceAuthzRules["/todo.v1.TodoService/CreateTodo"]
		resource, err := c.resolver.ResolveResource(rule, in)
		if err != nil {
			return nil, err
		}
		subject := _TodoServiceAuthzSubjectFromContext(ctx)
		switch rule.Mode {
		case authz.RuleModeScopedToken:
			token, decision, err := c.guard.RequireScopedToken(ctx, authz.ScopedTokenRequest{Subject: subject, Action: rule.Action, Resource: resource, Audience: rule.Audience, Rule: rule, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
			if token != "" {
				ctx = contextx.WithScopedToken(ctx, token)
			}
		case authz.RuleModeCheckOnly:
			decision, err := c.guard.Require(ctx, authz.CheckRequest{Subject: subject, Resource: resource, Permission: rule.Action, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
		case authz.RuleModeSelfCheck:
		// SELF_CHECK means the target resource service performs the final check.
		case authz.RuleModeUnspecified:
			return nil, authz.ErrInvalidRequest("authz rule mode must not be UNSPECIFIED")
		default:
			return nil, authz.ErrInvalidRequest("unsupported authz rule mode: " + string(rule.Mode))
		}
	}
	return c.raw.CreateTodo(ctx, in, opts...)
}

func (c *TodoServiceSecureClient) GetTodo(ctx context.Context, in *GetTodoRequest, opts ...grpc.CallOption) (*Todo, error) {
	if c != nil && c.guard != nil {
		rule := TodoServiceAuthzRules["/todo.v1.TodoService/GetTodo"]
		resource, err := c.resolver.ResolveResource(rule, in)
		if err != nil {
			return nil, err
		}
		subject := _TodoServiceAuthzSubjectFromContext(ctx)
		switch rule.Mode {
		case authz.RuleModeScopedToken:
			token, decision, err := c.guard.RequireScopedToken(ctx, authz.ScopedTokenRequest{Subject: subject, Action: rule.Action, Resource: resource, Audience: rule.Audience, Rule: rule, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
			if token != "" {
				ctx = contextx.WithScopedToken(ctx, token)
			}
		case authz.RuleModeCheckOnly:
			decision, err := c.guard.Require(ctx, authz.CheckRequest{Subject: subject, Resource: resource, Permission: rule.Action, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
		case authz.RuleModeSelfCheck:
		// SELF_CHECK means the target resource service performs the final check.
		case authz.RuleModeUnspecified:
			return nil, authz.ErrInvalidRequest("authz rule mode must not be UNSPECIFIED")
		default:
			return nil, authz.ErrInvalidRequest("unsupported authz rule mode: " + string(rule.Mode))
		}
	}
	return c.raw.GetTodo(ctx, in, opts...)
}

func (c *TodoServiceSecureClient) ListTodos(ctx context.Context, in *ListTodosRequest, opts ...grpc.CallOption) (*TodoSet, error) {
	if c != nil && c.guard != nil {
		rule := TodoServiceAuthzRules["/todo.v1.TodoService/ListTodos"]
		resource, err := c.resolver.ResolveResource(rule, in)
		if err != nil {
			return nil, err
		}
		subject := _TodoServiceAuthzSubjectFromContext(ctx)
		switch rule.Mode {
		case authz.RuleModeScopedToken:
			token, decision, err := c.guard.RequireScopedToken(ctx, authz.ScopedTokenRequest{Subject: subject, Action: rule.Action, Resource: resource, Audience: rule.Audience, Rule: rule, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
			if token != "" {
				ctx = contextx.WithScopedToken(ctx, token)
			}
		case authz.RuleModeCheckOnly:
			decision, err := c.guard.Require(ctx, authz.CheckRequest{Subject: subject, Resource: resource, Permission: rule.Action, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
		case authz.RuleModeSelfCheck:
		// SELF_CHECK means the target resource service performs the final check.
		case authz.RuleModeUnspecified:
			return nil, authz.ErrInvalidRequest("authz rule mode must not be UNSPECIFIED")
		default:
			return nil, authz.ErrInvalidRequest("unsupported authz rule mode: " + string(rule.Mode))
		}
	}
	return c.raw.ListTodos(ctx, in, opts...)
}

func (c *TodoServiceSecureClient) UpdateTodo(ctx context.Context, in *UpdateTodoRequest, opts ...grpc.CallOption) (*Todo, error) {
	if c != nil && c.guard != nil {
		rule := TodoServiceAuthzRules["/todo.v1.TodoService/UpdateTodo"]
		resource, err := c.resolver.ResolveResource(rule, in)
		if err != nil {
			return nil, err
		}
		subject := _TodoServiceAuthzSubjectFromContext(ctx)
		switch rule.Mode {
		case authz.RuleModeScopedToken:
			token, decision, err := c.guard.RequireScopedToken(ctx, authz.ScopedTokenRequest{Subject: subject, Action: rule.Action, Resource: resource, Audience: rule.Audience, Rule: rule, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
			if token != "" {
				ctx = contextx.WithScopedToken(ctx, token)
			}
		case authz.RuleModeCheckOnly:
			decision, err := c.guard.Require(ctx, authz.CheckRequest{Subject: subject, Resource: resource, Permission: rule.Action, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
		case authz.RuleModeSelfCheck:
		// SELF_CHECK means the target resource service performs the final check.
		case authz.RuleModeUnspecified:
			return nil, authz.ErrInvalidRequest("authz rule mode must not be UNSPECIFIED")
		default:
			return nil, authz.ErrInvalidRequest("unsupported authz rule mode: " + string(rule.Mode))
		}
	}
	return c.raw.UpdateTodo(ctx, in, opts...)
}

func (c *TodoServiceSecureClient) DeleteTodo(ctx context.Context, in *DeleteTodoRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	if c != nil && c.guard != nil {
		rule := TodoServiceAuthzRules["/todo.v1.TodoService/DeleteTodo"]
		resource, err := c.resolver.ResolveResource(rule, in)
		if err != nil {
			return nil, err
		}
		subject := _TodoServiceAuthzSubjectFromContext(ctx)
		switch rule.Mode {
		case authz.RuleModeScopedToken:
			token, decision, err := c.guard.RequireScopedToken(ctx, authz.ScopedTokenRequest{Subject: subject, Action: rule.Action, Resource: resource, Audience: rule.Audience, Rule: rule, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
			if token != "" {
				ctx = contextx.WithScopedToken(ctx, token)
			}
		case authz.RuleModeCheckOnly:
			decision, err := c.guard.Require(ctx, authz.CheckRequest{Subject: subject, Resource: resource, Permission: rule.Action, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
		case authz.RuleModeSelfCheck:
		// SELF_CHECK means the target resource service performs the final check.
		case authz.RuleModeUnspecified:
			return nil, authz.ErrInvalidRequest("authz rule mode must not be UNSPECIFIED")
		default:
			return nil, authz.ErrInvalidRequest("unsupported authz rule mode: " + string(rule.Mode))
		}
	}
	return c.raw.DeleteTodo(ctx, in, opts...)
}

func (c *TodoServiceSecureClient) WatchTodos(ctx context.Context, in *WatchTodosRequest, opts ...grpc.CallOption) (TodoService_WatchTodosClient, error) {
	return c.raw.WatchTodos(ctx, in, opts...)
}

func (c *TodoServiceSecureClient) SyncTodos(ctx context.Context, opts ...grpc.CallOption) (TodoService_SyncTodosClient, error) {
	return c.raw.SyncTodos(ctx, opts...)
}

func _TodoServiceAuthzSubjectFromContext(ctx context.Context) authz.SubjectRef {
	p := contextx.PrincipalFromContext(ctx)
	if p == nil {
		return authz.SubjectRef{}
	}
	typ := authz.SubjectTypeUser
	if strings.HasPrefix(p.SubjectID, "svc:") {
		typ = authz.SubjectTypeService
	}
	return authz.SubjectRef{Type: typ, ID: p.SubjectID}
}
