// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aisphere/options/v1/authz.proto

package optionsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthzMode int32

const (
	AuthzMode_AUTHZ_MODE_UNSPECIFIED AuthzMode = 0
	AuthzMode_CHECK_ONLY             AuthzMode = 1
	AuthzMode_SCOPED_TOKEN           AuthzMode = 2
	AuthzMode_SELF_CHECK             AuthzMode = 3
)

// Enum value maps for AuthzMode.
var (
	AuthzMode_name = map[int32]string{
		0: "AUTHZ_MODE_UNSPECIFIED",
		1: "CHECK_ONLY",
		2: "SCOPED_TOKEN",
		3: "SELF_CHECK",
	}
	AuthzMode_value = map[string]int32{
		"AUTHZ_MODE_UNSPECIFIED": 0,
		"CHECK_ONLY":             1,
		"SCOPED_TOKEN":           2,
		"SELF_CHECK":             3,
	}
)

func (x AuthzMode) Enum() *AuthzMode {
	p := new(AuthzMode)
	*p = x
	return p
}

func (x AuthzMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthzMode) Descriptor() protoreflect.EnumDescriptor {
	return file_aisphere_options_v1_authz_proto_enumTypes[0].Descriptor()
}

func (AuthzMode) Type() protoreflect.EnumType {
	return &file_aisphere_options_v1_authz_proto_enumTypes[0]
}

func (x AuthzMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthzMode.Descriptor instead.
func (AuthzMode) EnumDescriptor() ([]byte, []int) {
	return file_aisphere_options_v1_authz_proto_rawDescGZIP(), []int{0}
}

type AuthzRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Audience      string                 `protobuf:"bytes,3,opt,name=audience,proto3" json:"audience,omitempty"`
	Mode          AuthzMode              `protobuf:"varint,4,opt,name=mode,proto3,enum=aisphere.options.v1.AuthzMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthzRule) Reset() {
	*x = AuthzRule{}
	mi := &file_aisphere_options_v1_authz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthzRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthzRule) ProtoMessage() {}

func (x *AuthzRule) ProtoReflect() protoreflect.Message {
	mi := &file_aisphere_options_v1_authz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthzRule.ProtoReflect.Descriptor instead.
func (*AuthzRule) Descriptor() ([]byte, []int) {
	return file_aisphere_options_v1_authz_proto_rawDescGZIP(), []int{0}
}

func (x *AuthzRule) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuthzRule) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AuthzRule) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *AuthzRule) GetMode() AuthzMode {
	if x != nil {
		return x.Mode
	}
	return AuthzMode_AUTHZ_MODE_UNSPECIFIED
}

type AuditRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Risk          string                 `protobuf:"bytes,2,opt,name=risk,proto3" json:"risk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRule) Reset() {
	*x = AuditRule{}
	mi := &file_aisphere_options_v1_authz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRule) ProtoMessage() {}

func (x *AuditRule) ProtoReflect() protoreflect.Message {
	mi := &file_aisphere_options_v1_authz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRule.ProtoReflect.Descriptor instead.
func (*AuditRule) Descriptor() ([]byte, []int) {
	return file_aisphere_options_v1_authz_proto_rawDescGZIP(), []int{1}
}

func (x *AuditRule) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *AuditRule) GetRisk() string {
	if x != nil {
		return x.Risk
	}
	return ""
}

type CapabilityRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityRule) Reset() {
	*x = CapabilityRule{}
	mi := &file_aisphere_options_v1_authz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityRule) ProtoMessage() {}

func (x *CapabilityRule) ProtoReflect() protoreflect.Message {
	mi := &file_aisphere_options_v1_authz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityRule.ProtoReflect.Descriptor instead.
func (*CapabilityRule) Descriptor() ([]byte, []int) {
	return file_aisphere_options_v1_authz_proto_rawDescGZIP(), []int{2}
}

func (x *CapabilityRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CapabilityRule) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

var file_aisphere_options_v1_authz_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*AuthzRule)(nil),
		Field:         51001,
		Name:          "aisphere.options.v1.authz",
		Tag:           "bytes,51001,opt,name=authz",
		Filename:      "aisphere/options/v1/authz.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*AuditRule)(nil),
		Field:         51002,
		Name:          "aisphere.options.v1.audit",
		Tag:           "bytes,51002,opt,name=audit",
		Filename:      "aisphere/options/v1/authz.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*CapabilityRule)(nil),
		Field:         51003,
		Name:          "aisphere.options.v1.capability",
		Tag:           "bytes,51003,opt,name=capability",
		Filename:      "aisphere/options/v1/authz.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional aisphere.options.v1.AuthzRule authz = 51001;
	E_Authz = &file_aisphere_options_v1_authz_proto_extTypes[0]
	// optional aisphere.options.v1.AuditRule audit = 51002;
	E_Audit = &file_aisphere_options_v1_authz_proto_extTypes[1]
	// optional aisphere.options.v1.CapabilityRule capability = 51003;
	E_Capability = &file_aisphere_options_v1_authz_proto_extTypes[2]
)

var File_aisphere_options_v1_authz_proto protoreflect.FileDescriptor

const file_aisphere_options_v1_authz_proto_rawDesc = "" +
	"\n" +
	"\x1faisphere/options/v1/authz.proto\x12\x13aisphere.options.v1\x1a google/protobuf/descriptor.proto\"\x8f\x01\n" +
	"\tAuthzRule\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x1a\n" +
	"\baudience\x18\x03 \x01(\tR\baudience\x122\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x1e.aisphere.options.v1.AuthzModeR\x04mode\"5\n" +
	"\tAuditRule\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x12\n" +
	"\x04risk\x18\x02 \x01(\tR\x04risk\":\n" +
	"\x0eCapabilityRule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group*Y\n" +
	"\tAuthzMode\x12\x1a\n" +
	"\x16AUTHZ_MODE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"CHECK_ONLY\x10\x01\x12\x10\n" +
	"\fSCOPED_TOKEN\x10\x02\x12\x0e\n" +
	"\n" +
	"SELF_CHECK\x10\x03:V\n" +
	"\x05authz\x12\x1e.google.protobuf.MethodOptions\x18\xb9\x8e\x03 \x01(\v2\x1e.aisphere.options.v1.AuthzRuleR\x05authz:V\n" +
	"\x05audit\x12\x1e.google.protobuf.MethodOptions\x18\xba\x8e\x03 \x01(\v2\x1e.aisphere.options.v1.AuditRuleR\x05audit:e\n" +
	"\n" +
	"capability\x12\x1e.google.protobuf.MethodOptions\x18\xbb\x8e\x03 \x01(\v2#.aisphere.options.v1.CapabilityRuleR\n" +
	"capabilityB@Z>github.com/aisphereio/kernel/api/aisphere/options/v1;optionsv1b\x06proto3"

var (
	file_aisphere_options_v1_authz_proto_rawDescOnce sync.Once
	file_aisphere_options_v1_authz_proto_rawDescData []byte
)

func file_aisphere_options_v1_authz_proto_rawDescGZIP() []byte {
	file_aisphere_options_v1_authz_proto_rawDescOnce.Do(func() {
		file_aisphere_options_v1_authz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aisphere_options_v1_authz_proto_rawDesc), len(file_aisphere_options_v1_authz_proto_rawDesc)))
	})
	return file_aisphere_options_v1_authz_proto_rawDescData
}

var file_aisphere_options_v1_authz_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_aisphere_options_v1_authz_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_aisphere_options_v1_authz_proto_goTypes = []any{
	(AuthzMode)(0),                     // 0: aisphere.options.v1.AuthzMode
	(*AuthzRule)(nil),                  // 1: aisphere.options.v1.AuthzRule
	(*AuditRule)(nil),                  // 2: aisphere.options.v1.AuditRule
	(*CapabilityRule)(nil),             // 3: aisphere.options.v1.CapabilityRule
	(*descriptorpb.MethodOptions)(nil), // 4: google.protobuf.MethodOptions
}
var file_aisphere_options_v1_authz_proto_depIdxs = []int32{
	0, // 0: aisphere.options.v1.AuthzRule.mode:type_name -> aisphere.options.v1.AuthzMode
	4, // 1: aisphere.options.v1.authz:extendee -> google.protobuf.MethodOptions
	4, // 2: aisphere.options.v1.audit:extendee -> google.protobuf.MethodOptions
	4, // 3: aisphere.options.v1.capability:extendee -> google.protobuf.MethodOptions
	1, // 4: aisphere.options.v1.authz:type_name -> aisphere.options.v1.AuthzRule
	2, // 5: aisphere.options.v1.audit:type_name -> aisphere.options.v1.AuditRule
	3, // 6: aisphere.options.v1.capability:type_name -> aisphere.options.v1.CapabilityRule
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	4, // [4:7] is the sub-list for extension type_name
	1, // [1:4] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_aisphere_options_v1_authz_proto_init() }
func file_aisphere_options_v1_authz_proto_init() {
	if File_aisphere_options_v1_authz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aisphere_options_v1_authz_proto_rawDesc), len(file_aisphere_options_v1_authz_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_aisphere_options_v1_authz_proto_goTypes,
		DependencyIndexes: file_aisphere_options_v1_authz_proto_depIdxs,
		EnumInfos:         file_aisphere_options_v1_authz_proto_enumTypes,
		MessageInfos:      file_aisphere_options_v1_authz_proto_msgTypes,
		ExtensionInfos:    file_aisphere_options_v1_authz_proto_extTypes,
	}.Build()
	File_aisphere_options_v1_authz_proto = out.File
	file_aisphere_options_v1_authz_proto_goTypes = nil
	file_aisphere_options_v1_authz_proto_depIdxs = nil
}
