// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aisphere/access/v1/access.proto

package accessv1

import (
	v1 "github.com/aisphereio/kernel/api/aisphere/options/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Exposure int32

const (
	Exposure_EXPOSURE_UNSPECIFIED Exposure = 0
	Exposure_PUBLIC               Exposure = 1
	Exposure_AUTHENTICATED        Exposure = 2
	Exposure_AUTHORIZED           Exposure = 3
	Exposure_INTERNAL             Exposure = 4
	Exposure_SYSTEM               Exposure = 5
)

// Enum value maps for Exposure.
var (
	Exposure_name = map[int32]string{
		0: "EXPOSURE_UNSPECIFIED",
		1: "PUBLIC",
		2: "AUTHENTICATED",
		3: "AUTHORIZED",
		4: "INTERNAL",
		5: "SYSTEM",
	}
	Exposure_value = map[string]int32{
		"EXPOSURE_UNSPECIFIED": 0,
		"PUBLIC":               1,
		"AUTHENTICATED":        2,
		"AUTHORIZED":           3,
		"INTERNAL":             4,
		"SYSTEM":               5,
	}
)

func (x Exposure) Enum() *Exposure {
	p := new(Exposure)
	*p = x
	return p
}

func (x Exposure) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Exposure) Descriptor() protoreflect.EnumDescriptor {
	return file_aisphere_access_v1_access_proto_enumTypes[0].Descriptor()
}

func (Exposure) Type() protoreflect.EnumType {
	return &file_aisphere_access_v1_access_proto_enumTypes[0]
}

func (x Exposure) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Exposure.Descriptor instead.
func (Exposure) EnumDescriptor() ([]byte, []int) {
	return file_aisphere_access_v1_access_proto_rawDescGZIP(), []int{0}
}

type GatewayPublish int32

const (
	GatewayPublish_GATEWAY_PUBLISH_UNSPECIFIED GatewayPublish = 0
	GatewayPublish_ENABLED                     GatewayPublish = 1
	GatewayPublish_DISABLED                    GatewayPublish = 2
)

// Enum value maps for GatewayPublish.
var (
	GatewayPublish_name = map[int32]string{
		0: "GATEWAY_PUBLISH_UNSPECIFIED",
		1: "ENABLED",
		2: "DISABLED",
	}
	GatewayPublish_value = map[string]int32{
		"GATEWAY_PUBLISH_UNSPECIFIED": 0,
		"ENABLED":                     1,
		"DISABLED":                    2,
	}
)

func (x GatewayPublish) Enum() *GatewayPublish {
	p := new(GatewayPublish)
	*p = x
	return p
}

func (x GatewayPublish) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GatewayPublish) Descriptor() protoreflect.EnumDescriptor {
	return file_aisphere_access_v1_access_proto_enumTypes[1].Descriptor()
}

func (GatewayPublish) Type() protoreflect.EnumType {
	return &file_aisphere_access_v1_access_proto_enumTypes[1]
}

func (x GatewayPublish) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GatewayPublish.Descriptor instead.
func (GatewayPublish) EnumDescriptor() ([]byte, []int) {
	return file_aisphere_access_v1_access_proto_rawDescGZIP(), []int{1}
}

type Backend int32

const (
	Backend_BACKEND_UNSPECIFIED Backend = 0
	Backend_MEMORY              Backend = 1
	Backend_REDIS               Backend = 2
	Backend_EXTERNAL            Backend = 3
)

// Enum value maps for Backend.
var (
	Backend_name = map[int32]string{
		0: "BACKEND_UNSPECIFIED",
		1: "MEMORY",
		2: "REDIS",
		3: "EXTERNAL",
	}
	Backend_value = map[string]int32{
		"BACKEND_UNSPECIFIED": 0,
		"MEMORY":              1,
		"REDIS":               2,
		"EXTERNAL":            3,
	}
)

func (x Backend) Enum() *Backend {
	p := new(Backend)
	*p = x
	return p
}

func (x Backend) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Backend) Descriptor() protoreflect.EnumDescriptor {
	return file_aisphere_access_v1_access_proto_enumTypes[2].Descriptor()
}

func (Backend) Type() protoreflect.EnumType {
	return &file_aisphere_access_v1_access_proto_enumTypes[2]
}

func (x Backend) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Backend.Descriptor instead.
func (Backend) EnumDescriptor() ([]byte, []int) {
	return file_aisphere_access_v1_access_proto_rawDescGZIP(), []int{2}
}

type AccessPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exposure      Exposure               `protobuf:"varint,1,opt,name=exposure,proto3,enum=aisphere.access.v1.Exposure" json:"exposure,omitempty"`
	Authz         *Authz                 `protobuf:"bytes,2,opt,name=authz,proto3" json:"authz,omitempty"`
	Audit         *Audit                 `protobuf:"bytes,3,opt,name=audit,proto3" json:"audit,omitempty"`
	RateLimit     *RateLimit             `protobuf:"bytes,4,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	Breaker       *Breaker               `protobuf:"bytes,5,opt,name=breaker,proto3" json:"breaker,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	Gateway       *Gateway               `protobuf:"bytes,7,opt,name=gateway,proto3" json:"gateway,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessPolicy) Reset() {
	*x = AccessPolicy{}
	mi := &file_aisphere_access_v1_access_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessPolicy) ProtoMessage() {}

func (x *AccessPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_aisphere_access_v1_access_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessPolicy.ProtoReflect.Descriptor instead.
func (*AccessPolicy) Descriptor() ([]byte, []int) {
	return file_aisphere_access_v1_access_proto_rawDescGZIP(), []int{0}
}

func (x *AccessPolicy) GetExposure() Exposure {
	if x != nil {
		return x.Exposure
	}
	return Exposure_EXPOSURE_UNSPECIFIED
}

func (x *AccessPolicy) GetAuthz() *Authz {
	if x != nil {
		return x.Authz
	}
	return nil
}

func (x *AccessPolicy) GetAudit() *Audit {
	if x != nil {
		return x.Audit
	}
	return nil
}

func (x *AccessPolicy) GetRateLimit() *RateLimit {
	if x != nil {
		return x.RateLimit
	}
	return nil
}

func (x *AccessPolicy) GetBreaker() *Breaker {
	if x != nil {
		return x.Breaker
	}
	return nil
}

func (x *AccessPolicy) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AccessPolicy) GetGateway() *Gateway {
	if x != nil {
		return x.Gateway
	}
	return nil
}

type Gateway struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Publish       GatewayPublish         `protobuf:"varint,1,opt,name=publish,proto3,enum=aisphere.access.v1.GatewayPublish" json:"publish,omitempty"`
	Profiles      []string               `protobuf:"bytes,2,rep,name=profiles,proto3" json:"profiles,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gateway) Reset() {
	*x = Gateway{}
	mi := &file_aisphere_access_v1_access_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gateway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gateway) ProtoMessage() {}

func (x *Gateway) ProtoReflect() protoreflect.Message {
	mi := &file_aisphere_access_v1_access_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gateway.ProtoReflect.Descriptor instead.
func (*Gateway) Descriptor() ([]byte, []int) {
	return file_aisphere_access_v1_access_proto_rawDescGZIP(), []int{1}
}

func (x *Gateway) GetPublish() GatewayPublish {
	if x != nil {
		return x.Publish
	}
	return GatewayPublish_GATEWAY_PUBLISH_UNSPECIFIED
}

func (x *Gateway) GetProfiles() []string {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (x *Gateway) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Authz struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Audience      string                 `protobuf:"bytes,3,opt,name=audience,proto3" json:"audience,omitempty"`
	Mode          v1.AuthzMode           `protobuf:"varint,4,opt,name=mode,proto3,enum=aisphere.options.v1.AuthzMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authz) Reset() {
	*x = Authz{}
	mi := &file_aisphere_access_v1_access_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authz) ProtoMessage() {}

func (x *Authz) ProtoReflect() protoreflect.Message {
	mi := &file_aisphere_access_v1_access_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authz.ProtoReflect.Descriptor instead.
func (*Authz) Descriptor() ([]byte, []int) {
	return file_aisphere_access_v1_access_proto_rawDescGZIP(), []int{2}
}

func (x *Authz) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Authz) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Authz) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *Authz) GetMode() v1.AuthzMode {
	if x != nil {
		return x.Mode
	}
	return v1.AuthzMode(0)
}

type Audit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	Risk          string                 `protobuf:"bytes,3,opt,name=risk,proto3" json:"risk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Audit) Reset() {
	*x = Audit{}
	mi := &file_aisphere_access_v1_access_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Audit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Audit) ProtoMessage() {}

func (x *Audit) ProtoReflect() protoreflect.Message {
	mi := &file_aisphere_access_v1_access_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Audit.ProtoReflect.Descriptor instead.
func (*Audit) Descriptor() ([]byte, []int) {
	return file_aisphere_access_v1_access_proto_rawDescGZIP(), []int{3}
}

func (x *Audit) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Audit) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *Audit) GetRisk() string {
	if x != nil {
		return x.Risk
	}
	return ""
}

type RateLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Qps           float64                `protobuf:"fixed64,3,opt,name=qps,proto3" json:"qps,omitempty"`
	Burst         int32                  `protobuf:"varint,4,opt,name=burst,proto3" json:"burst,omitempty"`
	Backend       Backend                `protobuf:"varint,5,opt,name=backend,proto3,enum=aisphere.access.v1.Backend" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimit) Reset() {
	*x = RateLimit{}
	mi := &file_aisphere_access_v1_access_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimit) ProtoMessage() {}

func (x *RateLimit) ProtoReflect() protoreflect.Message {
	mi := &file_aisphere_access_v1_access_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimit.ProtoReflect.Descriptor instead.
func (*RateLimit) Descriptor() ([]byte, []int) {
	return file_aisphere_access_v1_access_proto_rawDescGZIP(), []int{4}
}

func (x *RateLimit) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *RateLimit) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RateLimit) GetQps() float64 {
	if x != nil {
		return x.Qps
	}
	return 0
}

func (x *RateLimit) GetBurst() int32 {
	if x != nil {
		return x.Burst
	}
	return 0
}

func (x *RateLimit) GetBackend() Backend {
	if x != nil {
		return x.Backend
	}
	return Backend_BACKEND_UNSPECIFIED
}

type Breaker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Breaker) Reset() {
	*x = Breaker{}
	mi := &file_aisphere_access_v1_access_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Breaker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Breaker) ProtoMessage() {}

func (x *Breaker) ProtoReflect() protoreflect.Message {
	mi := &file_aisphere_access_v1_access_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Breaker.ProtoReflect.Descriptor instead.
func (*Breaker) Descriptor() ([]byte, []int) {
	return file_aisphere_access_v1_access_proto_rawDescGZIP(), []int{5}
}

func (x *Breaker) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Breaker) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var file_aisphere_access_v1_access_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*AccessPolicy)(nil),
		Field:         51010,
		Name:          "aisphere.access.v1.policy",
		Tag:           "bytes,51010,opt,name=policy",
		Filename:      "aisphere/access/v1/access.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional aisphere.access.v1.AccessPolicy policy = 51010;
	E_Policy = &file_aisphere_access_v1_access_proto_extTypes[0]
)

var File_aisphere_access_v1_access_proto protoreflect.FileDescriptor

const file_aisphere_access_v1_access_proto_rawDesc = "" +
	"\n" +
	"\x1faisphere/access/v1/access.proto\x12\x12aisphere.access.v1\x1a\x1faisphere/options/v1/authz.proto\x1a google/protobuf/descriptor.proto\"\xee\x02\n" +
	"\fAccessPolicy\x128\n" +
	"\bexposure\x18\x01 \x01(\x0e2\x1c.aisphere.access.v1.ExposureR\bexposure\x12/\n" +
	"\x05authz\x18\x02 \x01(\v2\x19.aisphere.access.v1.AuthzR\x05authz\x12/\n" +
	"\x05audit\x18\x03 \x01(\v2\x19.aisphere.access.v1.AuditR\x05audit\x12<\n" +
	"\n" +
	"rate_limit\x18\x04 \x01(\v2\x1d.aisphere.access.v1.RateLimitR\trateLimit\x125\n" +
	"\abreaker\x18\x05 \x01(\v2\x1b.aisphere.access.v1.BreakerR\abreaker\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x125\n" +
	"\agateway\x18\a \x01(\v2\x1b.aisphere.access.v1.GatewayR\agateway\"w\n" +
	"\aGateway\x12<\n" +
	"\apublish\x18\x01 \x01(\x0e2\".aisphere.access.v1.GatewayPublishR\apublish\x12\x1a\n" +
	"\bprofiles\x18\x02 \x03(\tR\bprofiles\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\"\x8b\x01\n" +
	"\x05Authz\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x1a\n" +
	"\baudience\x18\x03 \x01(\tR\baudience\x122\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x1e.aisphere.options.v1.AuthzModeR\x04mode\"K\n" +
	"\x05Audit\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x12\n" +
	"\x04risk\x18\x03 \x01(\tR\x04risk\"\x96\x01\n" +
	"\tRateLimit\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x10\n" +
	"\x03qps\x18\x03 \x01(\x01R\x03qps\x12\x14\n" +
	"\x05burst\x18\x04 \x01(\x05R\x05burst\x125\n" +
	"\abackend\x18\x05 \x01(\x0e2\x1b.aisphere.access.v1.BackendR\abackend\"7\n" +
	"\aBreaker\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name*m\n" +
	"\bExposure\x12\x18\n" +
	"\x14EXPOSURE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06PUBLIC\x10\x01\x12\x11\n" +
	"\rAUTHENTICATED\x10\x02\x12\x0e\n" +
	"\n" +
	"AUTHORIZED\x10\x03\x12\f\n" +
	"\bINTERNAL\x10\x04\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\x05*L\n" +
	"\x0eGatewayPublish\x12\x1f\n" +
	"\x1bGATEWAY_PUBLISH_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aENABLED\x10\x01\x12\f\n" +
	"\bDISABLED\x10\x02*G\n" +
	"\aBackend\x12\x17\n" +
	"\x13BACKEND_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06MEMORY\x10\x01\x12\t\n" +
	"\x05REDIS\x10\x02\x12\f\n" +
	"\bEXTERNAL\x10\x03:Z\n" +
	"\x06policy\x12\x1e.google.protobuf.MethodOptions\x18\u008e\x03 \x01(\v2 .aisphere.access.v1.AccessPolicyR\x06policyB>Z<github.com/aisphereio/kernel/api/aisphere/access/v1;accessv1b\x06proto3"

var (
	file_aisphere_access_v1_access_proto_rawDescOnce sync.Once
	file_aisphere_access_v1_access_proto_rawDescData []byte
)

func file_aisphere_access_v1_access_proto_rawDescGZIP() []byte {
	file_aisphere_access_v1_access_proto_rawDescOnce.Do(func() {
		file_aisphere_access_v1_access_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aisphere_access_v1_access_proto_rawDesc), len(file_aisphere_access_v1_access_proto_rawDesc)))
	})
	return file_aisphere_access_v1_access_proto_rawDescData
}

var file_aisphere_access_v1_access_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_aisphere_access_v1_access_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_aisphere_access_v1_access_proto_goTypes = []any{
	(Exposure)(0),                      // 0: aisphere.access.v1.Exposure
	(GatewayPublish)(0),                // 1: aisphere.access.v1.GatewayPublish
	(Backend)(0),                       // 2: aisphere.access.v1.Backend
	(*AccessPolicy)(nil),               // 3: aisphere.access.v1.AccessPolicy
	(*Gateway)(nil),                    // 4: aisphere.access.v1.Gateway
	(*Authz)(nil),                      // 5: aisphere.access.v1.Authz
	(*Audit)(nil),                      // 6: aisphere.access.v1.Audit
	(*RateLimit)(nil),                  // 7: aisphere.access.v1.RateLimit
	(*Breaker)(nil),                    // 8: aisphere.access.v1.Breaker
	(v1.AuthzMode)(0),                  // 9: aisphere.options.v1.AuthzMode
	(*descriptorpb.MethodOptions)(nil), // 10: google.protobuf.MethodOptions
}
var file_aisphere_access_v1_access_proto_depIdxs = []int32{
	0,  // 0: aisphere.access.v1.AccessPolicy.exposure:type_name -> aisphere.access.v1.Exposure
	5,  // 1: aisphere.access.v1.AccessPolicy.authz:type_name -> aisphere.access.v1.Authz
	6,  // 2: aisphere.access.v1.AccessPolicy.audit:type_name -> aisphere.access.v1.Audit
	7,  // 3: aisphere.access.v1.AccessPolicy.rate_limit:type_name -> aisphere.access.v1.RateLimit
	8,  // 4: aisphere.access.v1.AccessPolicy.breaker:type_name -> aisphere.access.v1.Breaker
	4,  // 5: aisphere.access.v1.AccessPolicy.gateway:type_name -> aisphere.access.v1.Gateway
	1,  // 6: aisphere.access.v1.Gateway.publish:type_name -> aisphere.access.v1.GatewayPublish
	9,  // 7: aisphere.access.v1.Authz.mode:type_name -> aisphere.options.v1.AuthzMode
	2,  // 8: aisphere.access.v1.RateLimit.backend:type_name -> aisphere.access.v1.Backend
	10, // 9: aisphere.access.v1.policy:extendee -> google.protobuf.MethodOptions
	3,  // 10: aisphere.access.v1.policy:type_name -> aisphere.access.v1.AccessPolicy
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	10, // [10:11] is the sub-list for extension type_name
	9,  // [9:10] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_aisphere_access_v1_access_proto_init() }
func file_aisphere_access_v1_access_proto_init() {
	if File_aisphere_access_v1_access_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aisphere_access_v1_access_proto_rawDesc), len(file_aisphere_access_v1_access_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_aisphere_access_v1_access_proto_goTypes,
		DependencyIndexes: file_aisphere_access_v1_access_proto_depIdxs,
		EnumInfos:         file_aisphere_access_v1_access_proto_enumTypes,
		MessageInfos:      file_aisphere_access_v1_access_proto_msgTypes,
		ExtensionInfos:    file_aisphere_access_v1_access_proto_extTypes,
	}.Build()
	File_aisphere_access_v1_access_proto = out.File
	file_aisphere_access_v1_access_proto_goTypes = nil
	file_aisphere_access_v1_access_proto_depIdxs = nil
}
